# Generated by Django 4.0 on 2026-01-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fm', '0010_alter_supplier_tax_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Generated By')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSalesReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sold_items', models.PositiveIntegerField(default=0, verbose_name='Number of Sold Items')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Sales')),
                ('total_cogs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total COGS')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.productsalesreport', verbose_name='Product Sales Report')),
            ],
        ),
    ]
