# Generated by Django 4.0 on 2026-01-02 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fm', '0010_alter_supplier_tax_class'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsalesreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Sales Report', 'verbose_name_plural': 'Product Sales Reports'},
        ),
        migrations.AlterModelOptions(
            name='productsalesreportitem',
            options={'ordering': ['product'], 'verbose_name': 'Product Sales Report Item', 'verbose_name_plural': 'Product Sales Report Items'},
        ),
        migrations.CreateModel(
            name='InventoryCountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('inventory_date', models.DateField(default=django.utils.timezone.now, verbose_name='Inventory Date')),
                ('warehouse_count_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=20, verbose_name='Warehouse Count Status')),
                ('store_count_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=20, verbose_name='Store Count Status')),
                ('overall_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=20, verbose_name='Overall Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Inventory Report',
                'verbose_name_plural': 'Inventory Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Store', 'Store')], default='Warehouse', max_length=20, verbose_name='Location')),
                ('cycle', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Cycle')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.inventorycountreport', verbose_name='Inventory Report')),
            ],
        ),
    ]
