# Generated by Django 4.0 on 2026-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_productsalesreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountreport',
            name='store_cycle_1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Store Cycle 1'),
        ),
        migrations.AddField(
            model_name='inventorycountreport',
            name='store_cycle_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Store Cycle 2'),
        ),
        migrations.AddField(
            model_name='inventorycountreport',
            name='store_cycle_3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Store Cycle 3'),
        ),
        migrations.AddField(
            model_name='inventorycountreport',
            name='warehouse_cycle_1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Warehouse Cycle 1'),
        ),
        migrations.AddField(
            model_name='inventorycountreport',
            name='warehouse_cycle_2',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Warehouse Cycle 2'),
        ),
        migrations.AddField(
            model_name='inventorycountreport',
            name='warehouse_cycle_3',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Warehouse Cycle 3'),
        ),
    ]
