# Generated by Django 4.0 on 2026-01-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_inventorycountreport_store_cycle_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycountitem',
            options={'ordering': ['product__category__category_description', 'product__full_description'], 'verbose_name': 'Inventory Count Item', 'verbose_name_plural': 'Inventory Count Items'},
        ),
        migrations.RemoveField(
            model_name='inventorycountitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventorycountitem',
            name='expected_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Expected Count'),
        ),
        migrations.AddField(
            model_name='inventorycountitem',
            name='physical_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Physical Count'),
        ),
        migrations.AddField(
            model_name='inventorycountitem',
            name='variance',
            field=models.PositiveIntegerField(default=0, verbose_name='Variance'),
        ),
    ]
