# Generated by Django 4.0 on 2026-01-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_inventorycountitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycountitem',
            name='variance',
            field=models.IntegerField(default=0, verbose_name='Variance'),
        ),
    ]
