# Generated by Django 4.0 on 2022-01-20 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested at')),
                ('approved_at', models.DateTimeField(default=None, null=True, verbose_name='Approved at')),
                ('released_at', models.DateTimeField(default=None, null=True, verbose_name='Released at')),
                ('received_at', models.DateTimeField(default=None, null=True, verbose_name='Received at')),
                ('rejected_at', models.DateTimeField(default=None, null=True, verbose_name='Rejected at')),
                ('reject_reason', models.CharField(default=None, max_length=250, null=True, verbose_name='Reject Reason')),
                ('process_step', models.PositiveSmallIntegerField(default=1, verbose_name='Process Step')),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rv_approver', to='auth.user')),
                ('received_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rv_receiver', to='auth.user')),
                ('rejected_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rv_rejecter', to='auth.user')),
                ('released_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rv_releaser', to='auth.user')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rv_requester', to='auth.user')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('pk'), descending=True, nulls_first=True)],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Date Received')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Supplier's Price")),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('remaining_stocks', models.PositiveIntegerField(default=0, verbose_name='Remaining Stocks')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Received By')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Supplier's Price")),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('remaining_stocks', models.PositiveIntegerField(default=0, verbose_name='Remaining Stocks')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
                ('requisition_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.requisitionvoucher', verbose_name='Source from requisition voucher')),
                ('warehouse_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.warehousestock', verbose_name='Source from warehouse stock')),
            ],
        ),
        migrations.CreateModel(
            name='RV_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fm.product')),
                ('rv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.requisitionvoucher', verbose_name='Requisition Voucher')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.PositiveSmallIntegerField(verbose_name='Location where the transaction happened. 0=Warehouse; 1=Store')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('remarks', models.CharField(max_length=250, verbose_name='Remarks')),
                ('performed_on', models.DateField(auto_now_add=True, verbose_name='Performed on')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Performed By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['-pk', 'product'],
            },
        ),
    ]
