# Generated by Django 4.0 on 2021-12-31 07:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitionvoucher',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('pk'), descending=True, nulls_first=True)]},
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='reject_reason',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Reject Reason'),
        ),
        migrations.AlterField(
            model_name='requisitionvoucher',
            name='cancelled_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Cancelled at'),
        ),
    ]
