# Generated by Django 4.0 on 2022-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'ordering': ['-performed_on', 'product']},
        ),
        migrations.AddField(
            model_name='producthistory',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Current Balance'),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='item_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Item Count'),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='status',
            field=models.CharField(default='Pending', max_length=15, verbose_name='Status'),
        ),
    ]
