# Generated by Django 4.0 on 2022-05-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_producthistory_options_producthistory_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'ordering': ['-performed_on', 'product'], 'verbose_name_plural': 'Product History'},
        ),
    ]
