# Generated by Django 4.0 on 2022-01-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0008_delete_productpricing'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stocks', '0002_alter_requisitionvoucher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rv_product',
            options={'ordering': ['product']},
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='received_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Received at'),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='received_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rv_receiver', to='auth.user'),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='released_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Released at'),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='released_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rv_releaser', to='auth.user'),
        ),
        migrations.AlterUniqueTogether(
            name='rv_product',
            unique_together={('rv', 'product')},
        ),
    ]
