# Generated by Django 4.0 on 2022-05-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fm', '0009_product_avg_inventory_product_cogs_product_itr'),
        ('stocks', '0003_alter_producthistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(help_text='Negative to reduce the quantity, positive to increase the quantity.', verbose_name='By how many?')),
                ('reason', models.CharField(max_length=250, verbose_name='Reason for adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Checked at')),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved at')),
                ('performed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Performed at')),
                ('cancelled_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Cancelled at')),
                ('status', models.CharField(default='Submitted', max_length=10, verbose_name='Status')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_approver', to='auth.user')),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_canceller', to='auth.user')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_checker', to='auth.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_requester', to='auth.user')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_performer', to='auth.user')),
                ('product', models.ForeignKey(help_text='Product to adjust', on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['-created_at', 'product'],
            },
        ),
    ]
