# Generated by Django 4.0 on 2022-01-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stocks', '0003_alter_rv_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionvoucher',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='requisitionvoucher',
            name='cancelled_by',
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='rejected_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Rejected at'),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='rejected_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rv_rejecter', to='auth.user'),
        ),
    ]
