# Generated by Django 4.0 on 2022-05-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stocks', '0004_stockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_approver', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_canceller', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='checked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_checker', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='performed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_performer', to='auth.user'),
        ),
    ]
