# Generated by Django 3.2.7 on 2022-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_remove_requisitionvoucher_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rv_product',
            name='received_qty',
        ),
        migrations.RemoveField(
            model_name='rv_product',
            name='released_qty',
        ),
        migrations.RemoveField(
            model_name='rv_product',
            name='requested_qty',
        ),
        migrations.RemoveField(
            model_name='storestock',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='storestock',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='storestock',
            name='released_by',
        ),
        migrations.AddField(
            model_name='rv_product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
