# Generated by Django 4.0 on 2022-01-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20220101_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'ordering': ['-performed_on', 'product']},
        ),
        migrations.AlterUniqueTogether(
            name='rv_product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='location',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Location where the transaction happened. 0=Warehouse; 1=Store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
