# Generated by Django 4.0 on 2022-05-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stockadjustment_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Warehouse'), (1, 'Store')], default=0, help_text='Where will the adjustment be made?', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
