# Generated by Django 4.0 on 2022-01-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_producthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
