# Generated by Django 4.0 on 2026-01-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stockadjustment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestock',
            name='requisition_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.requisitionvoucher', verbose_name='Source from requisition voucher'),
        ),
        migrations.AlterField(
            model_name='storestock',
            name='warehouse_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.warehousestock', verbose_name='Source from warehouse stock'),
        ),
    ]
