# Generated by Django 4.0 on 2022-01-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_producthistory_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'ordering': ['-pk', 'product']},
        ),
    ]
