from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User
from fm.models import Product
from django.utils import timezone


####################################################
# Product Sales Report
####################################################

class ProductSalesReport(models.Model):
    generated_by = models.ForeignKey(
        User,
        verbose_name=_("Generated By"),
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        _("Created At"),
        auto_now_add=True
    )

    class Meta:
        verbose_name = _("Product Sales Report")
        verbose_name_plural = _("Product Sales Reports")
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.generated_by} - {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"


class ProductSalesReportItem(models.Model):
    report = models.ForeignKey(
        ProductSalesReport,
        verbose_name=_("Product Sales Report"),
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        verbose_name=_("Product"),
        on_delete=models.CASCADE
    )
    number_of_sold_items = models.PositiveIntegerField(
        _("Number of Sold Items"),
        default=0
    )
    total_sales = models.DecimalField(
        _("Total Sales"),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    total_cogs = models.DecimalField(
        _("Total COGS"),
        max_digits=10,
        decimal_places=2,
        default=0
    )

    class Meta:
        verbose_name = _("Product Sales Report Item")
        verbose_name_plural = _("Product Sales Report Items")
        ordering = ["product"]

    def __str__(self):
        return f"{self.product} - {self.number_of_sold_items}"



####################################################
# Inventory Count Report
####################################################

class InventoryCountReport(models.Model):
    INVENTORY_COUNT_STATUS = (
        ("In Progress", "In Progress"),
        ("Completed", "Completed"),
        ("Cancelled", "Cancelled"),
    )

    description = models.TextField(
        verbose_name=_("Description"),
        blank=True,
        null=True
    )
    inventory_date = models.DateField(
        verbose_name=_("Inventory Date"),
        default=timezone.now
    )
    warehouse_count_status = models.CharField(
        verbose_name=_("Warehouse Count Status"),
        max_length=20,
        choices=INVENTORY_COUNT_STATUS,
        default="In Progress"
    )
    store_count_status = models.CharField(
        verbose_name=_("Store Count Status"),
        max_length=20,
        choices=INVENTORY_COUNT_STATUS,
        default="In Progress"
    )
    overall_status = models.CharField(
        verbose_name=_("Overall Status"),
        max_length=20,
        choices=INVENTORY_COUNT_STATUS,
        default="In Progress"
    )
    generated_by = models.ForeignKey(
        User,
        verbose_name=_("Generated By"),
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        _("Created At"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        _("Updated At"),
        auto_now=True
    )
    warehouse_cycle_1 = models.DateTimeField(
        verbose_name=_("Warehouse Cycle 1"),
        default = None,
        blank=True,
        null=True
    )
    warehouse_cycle_2 = models.DateTimeField(
        verbose_name=_("Warehouse Cycle 2"),
        default = None,
        blank=True,
        null=True
    )
    warehouse_cycle_3 = models.DateTimeField(
        verbose_name=_("Warehouse Cycle 3"),
        default = None,
        blank=True,
        null=True
    )
    store_cycle_1 = models.DateTimeField(
        verbose_name=_("Store Cycle 1"),
        default = None,
        blank=True,
        null=True
    )
    store_cycle_2 = models.DateTimeField(
        verbose_name=_("Store Cycle 2"),
        blank=True,
        null=True
    )
    store_cycle_3 = models.DateTimeField(
        verbose_name=_("Store Cycle 3"),
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = _("Inventory Report")
        verbose_name_plural = _("Inventory Reports")
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.generated_by} - {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"

    def save(self, *args, **kwargs):
        if self.warehouse_count_status == "Completed" and self.store_count_status == "Completed":
            self.overall_status = "Completed"
        super().save(*args, **kwargs)

    def last_store_cycle(self):
        if self.store_cycle_3: return 3
        if self.store_cycle_2: return 2
        if self.store_cycle_1: return 1
        return 0

    def was_store_count_completed(self):
        return self.store_count_status == "Completed"

    def last_warehouse_cycle(self):
        if self.warehouse_cycle_3: return 3
        if self.warehouse_cycle_2: return 2
        if self.warehouse_cycle_1: return 1
        return 0

    def get_last_cycle(self, location):
        if location.lower() == "warehouse":
            return self.last_warehouse_cycle()
        elif location.lower() == "store":
            return self.last_store_cycle()
        return 0

    def update_completed_date(self, location, cycle):
        if location.lower() == "warehouse":
            if cycle == 1:
                self.warehouse_cycle_1 = timezone.now()
            elif cycle == 2:
                self.warehouse_cycle_2 = timezone.now()
            elif cycle == 3:
                self.warehouse_cycle_3 = timezone.now()
        elif location.lower() == "store":
            if cycle == 1:
                self.store_cycle_1 = timezone.now()
            elif cycle == 2:
                self.store_cycle_2 = timezone.now()
            elif cycle == 3:
                self.store_cycle_3 = timezone.now()
        self.save()

    def was_warehouse_count_completed(self):
        return self.warehouse_count_status == "Completed"

    def get_summary(self, location, cycle):
        inventory_items = InventoryCountItem.objects.filter(report=self, location=location, cycle=cycle)
        if inventory_items.exists():
            count = inventory_items.count()
            shortages = inventory_items.filter(variance__lt=0).count()
            overages = inventory_items.filter(variance__gt=0).count()
            variance = shortages + overages
            return {
                'count': count,
                'shortages': shortages,
                'overages': overages,
                'variance': variance
            }        
        return None

    def was_completed(self):
        return self.overall_status == "Completed"

class InventoryCountItem(models.Model):
    MAX_CYCLES = 3
    LOCATION_CHOICES = (
        ("Warehouse", "Warehouse"),
        ("Store", "Store"),
    )

    report = models.ForeignKey(
        InventoryCountReport,
        verbose_name=_("Inventory Report"),
        on_delete=models.CASCADE
    )
    location = models.CharField(
        verbose_name=_("Location"),
        max_length=20,
        choices=LOCATION_CHOICES,
        default="Warehouse"
    )
    cycle = models.PositiveIntegerField(
        _("Cycle"),
        default=1,
        validators=[
            MaxValueValidator(MAX_CYCLES)
        ]
    )
    product = models.ForeignKey(
        Product,
        verbose_name=_("Product"),
        on_delete=models.CASCADE
    )
    physical_count = models.PositiveIntegerField(
        _("Physical Count"),
        default=0
    )
    expected_count = models.PositiveIntegerField(
        _("Expected Count"),
        default=0
    )
    variance = models.IntegerField(
        _("Variance"),
        default=0
    )

    class Meta:
        verbose_name = _("Inventory Count Item")
        verbose_name_plural = _("Inventory Count Items")
        ordering = ["product__category__category_description", "product__full_description"]