from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from fm.models import Product

class ProductSalesReport(models.Model):
    generated_by = models.ForeignKey(
        User,
        verbose_name=_("Generated By"),
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        _("Created At"),
        auto_now_add=True
    )

    class Meta:
        verbose_name = _("Product Sales Report")
        verbose_name_plural = _("Product Sales Reports")
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.generated_by} - {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"


class ProductSalesReportItem(models.Model):
    report = models.ForeignKey(
        ProductSalesReport,
        verbose_name=_("Product Sales Report"),
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        verbose_name=_("Product"),
        on_delete=models.CASCADE
    )
    number_of_sold_items = models.PositiveIntegerField(
        _("Number of Sold Items"),
        default=0
    )
    total_sales = models.DecimalField(
        _("Total Sales"),
        max_digits=10,
        decimal_places=2,
        default=0
    )
    total_cogs = models.DecimalField(
        _("Total COGS"),
        max_digits=10,
        decimal_places=2,
        default=0
    )

    class Meta:
        verbose_name = _("Product Sales Report Item")
        verbose_name_plural = _("Product Sales Report Items")
        ordering = ["product"]

    def __str__(self):
        return f"{self.product} - {self.number_of_sold_items}"