# Generated by Django 3.2.7 on 2021-12-22 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fm', '0005_category_oic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Sequence Number')),
                ('po_date', models.DateField(verbose_name='PO Date')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Notes')),
                ('po_total', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Total Amount')),
                ('process_step', models.PositiveSmallIntegerField(choices=[(1, 'Purchaser'), (2, 'Officer-In-Charge'), (3, 'Audit Committee'), (4, 'General Manager'), (5, 'Approved'), (6, 'Rejected'), (7, 'Cancelled')], default=1, verbose_name='Step')),
                ('prepared_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Prepared at')),
                ('oic_checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved by OIC at')),
                ('audit_checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved by Audit at')),
                ('gm_checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved by GM at')),
                ('rejected_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Rejected at')),
                ('reject_reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason for rejection')),
                ('received_date', models.DateField(verbose_name='Date Received')),
                ('reference_number', models.CharField(max_length=250, verbose_name='Reference Number')),
                ('audit_checker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_audit_checked', to=settings.AUTH_USER_MODEL, verbose_name='Audit Committee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fm.category', verbose_name='Category')),
                ('gm_checker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_approved', to=settings.AUTH_USER_MODEL, verbose_name='General Manager')),
                ('oic_checker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_oic_checked', to=settings.AUTH_USER_MODEL, verbose_name='Officer-In-Charge')),
                ('prepared_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_prepared', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by')),
                ('received_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Received by')),
                ('rejected_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_canceller', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fm.supplier', verbose_name='Supplier')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('sequence_number'), descending=True, nulls_first=True)],
            },
        ),
        migrations.CreateModel(
            name='PO_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Unit Price')),
                ('ordered_quantity', models.PositiveIntegerField(verbose_name='Ordered Quantity')),
                ('received_qty', models.PositiveIntegerField(default=0, verbose_name='Received Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fm.product', verbose_name='Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseorder')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
