# Generated by Django 4.0 on 2022-01-20 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField(verbose_name='PO Date')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Notes')),
                ('po_total', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Total Amount')),
                ('parent_po', models.PositiveIntegerField(default=None, help_text='When PO is split for back-order, this is the source PO.', null=True, verbose_name='Parent PO')),
                ('process_step', models.PositiveSmallIntegerField(choices=[(1, 'Purchaser'), (2, 'Officer-In-Charge'), (3, 'Audit Committee'), (4, 'General Manager'), (5, 'Approved'), (6, 'Rejected'), (7, 'Cancelled')], default=1, verbose_name='Step')),
                ('prepared_at', models.DateTimeField(auto_now_add=True, verbose_name='Prepared at')),
                ('oic_checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved by OIC at')),
                ('audit_checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved by Audit at')),
                ('gm_checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved by GM at')),
                ('rejected_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Rejected at')),
                ('reject_reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason for rejection')),
                ('received_date', models.DateField(blank=True, default=None, null=True, verbose_name='Date Received')),
                ('reference_number', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reference Number')),
                ('is_open', models.BooleanField(default=True, verbose_name='Is open?')),
                ('is_receiving_now', models.BooleanField(default=False, verbose_name='Is the user receiving stocks now?')),
                ('has_cancelled_items', models.BooleanField(default=False, verbose_name='Is this PO contains cancelled items?')),
                ('audit_checker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_audit_checked', to='auth.user', verbose_name='Audit Committee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fm.category', verbose_name='Category')),
                ('gm_checker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_approved', to='auth.user', verbose_name='General Manager')),
                ('oic_checker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_oic_checked', to='auth.user', verbose_name='Officer-In-Charge')),
                ('prepared_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_prepared', to='auth.user', verbose_name='Prepared by')),
                ('received_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_receiver', to='auth.user', verbose_name='Received by')),
                ('rejected_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='po_canceller', to='auth.user', verbose_name='Rejected by')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fm.supplier', verbose_name='Supplier')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('pk'), descending=True, nulls_first=True)],
            },
        ),
        migrations.CreateModel(
            name='PO_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Unit Price')),
                ('ordered_quantity', models.PositiveIntegerField(verbose_name='Ordered Quantity')),
                ('received_qty', models.PositiveIntegerField(default=0, verbose_name='Received Quantity')),
                ('receive_now', models.PositiveIntegerField(default=0, verbose_name='Receive Now')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fm.product', verbose_name='Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseorder')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
