# Generated by Django 3.2.7 on 2021-12-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Is open?'),
        ),
    ]
