# Generated by Django 4.0 on 2022-04-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_po_product_has_received_po_product_po_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='po_product',
            options={'ordering': ['-purchase_order', 'product'], 'verbose_name': 'PO Product', 'verbose_name_plural': 'PO Products'},
        ),
    ]
