# Generated by Django 3.2.7 on 2021-12-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseorder_parent_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='prepared_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Prepared at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference_number',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reference Number'),
        ),
    ]
