# Generated by Django 4.0 on 2022-04-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_po_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_total',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='parent_po',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='When PO is split for back-order, this is the source PO.', null=True, verbose_name='Parent PO'),
        ),
    ]
