# Generated by Django 4.0 on 2021-12-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20211223_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='sequence_number',
        ),
    ]
