# Generated by Django 4.0 on 2025-12-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_purchaseorder_po_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_product',
            name='is_price_originally_set',
            field=models.BooleanField(default=False, verbose_name='Price Originally Set?'),
        ),
    ]
