# Generated by Django 4.0 on 2021-12-25 08:49

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_remove_purchaseorder_sequence_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('pk'), descending=True, nulls_first=True)]},
        ),
    ]
