# Generated by Django 4.0 on 2021-12-27 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0006_product_price_review'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('purchases', '0006_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_product',
            name='receive_now',
            field=models.PositiveIntegerField(default=0, verbose_name='Receive Now'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Date Received')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Supplier's Price")),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('remaining_stocks', models.PositiveIntegerField(default=0, verbose_name='Remaining Stocks')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Received By')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Date Received')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Supplier's Price")),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('remaining_stocks', models.PositiveIntegerField(default=0, verbose_name='Remaining Stocks')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Received By')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('remarks', models.CharField(max_length=250, verbose_name='Remarks')),
                ('performed_on', models.DateField(auto_now_add=True, verbose_name='Performed on')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Performed By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
            ],
        ),
    ]
