# Generated by Django 4.0 on 2021-12-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_po_product_receive_now_warehousestock_storestock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_receiving_now',
            field=models.BooleanField(default=False, verbose_name='Is the user receiving stocks now?'),
        ),
    ]
