# Generated by Django 4.0 on 2021-12-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchaseorder_is_receiving_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='has_cancelled_items',
            field=models.BooleanField(default=False, verbose_name='Is this PO contains cancelled items?'),
        ),
    ]
