# Generated by Django 4.0 on 2022-01-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0008_delete_productpricing'),
        ('purchases', '0010_remove_storestock_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='po_product',
            unique_together={('purchase_order', 'product')},
        ),
    ]
