# Generated by Django 4.0 on 2022-01-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_po_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='po_product',
            unique_together=set(),
        ),
    ]
