# Generated by Django 4.0 on 2022-05-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='Transaction Type')),
                ('reference_num', models.CharField(max_length=50, verbose_name='Reference Number')),
                ('adjustment_detail', models.TextField(verbose_name='Adjustment Detail')),
                ('reason', models.CharField(max_length=250, verbose_name='Reason for adjustment')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested at')),
                ('checked_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Checked at')),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved at')),
                ('performed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Performed at')),
                ('cancelled_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Cancelled at')),
                ('status', models.CharField(default='Submitted', max_length=10, verbose_name='Status')),
                ('approved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entryadj_approver', to='auth.user')),
                ('cancelled_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entryadj_canceller', to='auth.user')),
                ('checked_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entryadj_checker', to='auth.user')),
                ('performed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entryadj_performer', to='auth.user')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entryadj_requester', to='auth.user')),
            ],
            options={
                'ordering': ['-requested_at', 'transaction_type'],
            },
        ),
    ]
