# Generated by Django 4.0 on 2025-09-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(auto_now_add=True)),
                ('import_time', models.TimeField(auto_now_add=True)),
                ('import_status', models.CharField(default='Pending', max_length=20)),
                ('import_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20)),
                ('full_description', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('uom', models.CharField(max_length=20)),
                ('reorder_point', models.IntegerField()),
                ('ceiling_qty', models.IntegerField()),
                ('srp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_qty', models.IntegerField()),
                ('tax_type', models.CharField(choices=[('V', 'VAT'), ('E', 'VAT Exempt'), ('Z', 'Zero Rated')], max_length=1)),
                ('is_prime_commodity', models.BooleanField(default=False)),
                ('is_consigned', models.BooleanField(default=False)),
                ('is_buyer_info_required', models.BooleanField(default=False)),
                ('other_info', models.CharField(max_length=250)),
                ('suppliers', models.CharField(max_length=250)),
                ('warehouse_qty', models.IntegerField()),
                ('store_qty', models.IntegerField()),
                ('import_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import.import')),
            ],
        ),
    ]
