# Generated by Django 4.0 on 2025-09-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import',
            options={'ordering': ['-import_date', '-import_time'], 'verbose_name': 'Import', 'verbose_name_plural': 'Imports'},
        ),
        migrations.AlterModelOptions(
            name='importitem',
            options={'ordering': ['-import_ref', 'full_description'], 'verbose_name': 'Import Item', 'verbose_name_plural': 'Import Items'},
        ),
        migrations.AddField(
            model_name='import',
            name='import_type',
            field=models.CharField(choices=[('D', 'Data'), ('S', 'Supplier')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_info', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tax_type', models.CharField(choices=[('V', 'VAT'), ('E', 'VAT Exempt'), ('Z', 'Zero Rated')], max_length=1)),
                ('tin', models.CharField(max_length=20)),
                ('deducts_vat', models.BooleanField(default=False)),
                ('import_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import.import')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-import_ref', 'supplier_name'],
            },
        ),
    ]
