# Generated by Django 4.0 on 2025-09-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_alter_import_options_alter_importitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='import_type',
            field=models.CharField(choices=[('D', 'Data'), ('S', 'Supplier'), ('C', 'Creditor')], max_length=1),
        ),
        migrations.CreateModel(
            name='CreditorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_type', models.CharField(choices=[('Member', 'Member'), ('Group', 'Group Creditor')], max_length=10)),
                ('id_number', models.CharField(blank=True, default=None, max_length=5, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('tin', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('import_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import.import')),
            ],
            options={
                'verbose_name': 'Creditor',
                'verbose_name_plural': 'Creditors',
                'ordering': ['-import_ref', 'name'],
            },
        ),
    ]
