# Generated by Django 4.0 on 2021-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_description', models.CharField(help_text='Use singular form.', max_length=50, verbose_name='Category description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10, verbose_name='Status')),
            ],
            options={
                'ordering': ['category_description'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='Supplier Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('tax_class', models.CharField(blank=True, choices=[('Taxable', 'Taxable'), ('Non-Taxable', 'Non-Taxable'), ('Tax Exempt', 'Tax Exempt')], default=None, max_length=50, null=True, verbose_name='Tax Classification')),
                ('tin', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Tax Identification Number')),
                ('less_vat', models.BooleanField(default=False, verbose_name='Supplier deducts VAT from total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('activated_at', models.DateTimeField(null=True, verbose_name='Activated at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last updated at')),
                ('cancelled_at', models.DateTimeField(default=None, null=True, verbose_name='Cancelled at')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10, verbose_name='Status')),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_description', models.CharField(help_text='Use singular form.', max_length=50, verbose_name='Unit of measure')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10, verbose_name='Status')),
            ],
            options={
                'ordering': ['uom_description'],
            },
        ),
    ]
