# Generated by Django 4.0 on 2021-12-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Information'),
        ),
    ]
