# Generated by Django 3.2.7 on 2022-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('V', 'VAT'), ('X', 'VAT Exempt'), ('Z', 'Zero Rated')], default='V', max_length=1, verbose_name='Tax Type'),
        ),
    ]
