# Generated by Django 4.0 on 2021-12-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fm', '0002_remove_supplier_contact_number_supplier_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Barcode')),
                ('full_description', models.CharField(max_length=250, unique=True, verbose_name='Product description')),
                ('short_name', models.CharField(help_text='This will appear in the receipt', max_length=50, unique=True, verbose_name='Short name')),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text="The level (quantity) when you will need to place an order so you won't run out of stock.", verbose_name='Reorder Point')),
                ('economic_order_qty', models.PositiveIntegerField(default=0, help_text='The optimal amount of inventory you should purchase in order to meet your demand while minimizing your holding and storage costs.', verbose_name='Economic Order Quantity')),
                ('suggested_retail_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Suggested Retail Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Selling Price')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Wholesale Price')),
                ('wholesale_qty', models.IntegerField(default=0, help_text='Quantity to consider as wholesale', verbose_name='Wholesale Quantity')),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT'), ('VAT Exempt', 'VAT Exempt'), ('Zero-Rated', 'Zero Rated')], default='VAT', max_length=15, verbose_name='Tax Type')),
                ('is_consignment', models.BooleanField(default=False, help_text='Is this a consigned product?', verbose_name='Consigned product?')),
                ('is_buyer_info_needed', models.BooleanField(default=False, help_text="Do you need to get the buyer's information upon purchase?", verbose_name="Buyer's information needed?")),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='Other Information')),
                ('for_price_review', models.BooleanField(default=False, verbose_name='For price review?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('price_updated_on', models.DateField(default=None, null=True, verbose_name='Price updated on')),
                ('cancelled_at', models.DateTimeField(default=None, null=True, verbose_name='Cancelled at')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fm.category', verbose_name='Category')),
                ('suppliers', models.ManyToManyField(to='fm.Supplier')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fm.unitofmeasure', verbose_name='Unit of Measurement')),
            ],
            options={
                'ordering': ['full_description'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Selling Price')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Wholesale Price')),
                ('price_updated_on', models.DateField(default=None, null=True, verbose_name='Price updated on')),
                ('price_tagged_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user', verbose_name='Price tagged by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
            ],
        ),
    ]
