# Generated by Django 3.2.7 on 2022-02-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0002_alter_product_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('V', 'VAT'), ('E', 'VAT Exempt'), ('Z', 'Zero Rated')], default='V', max_length=1, verbose_name='Tax Type'),
        ),
    ]
