# Generated by Django 3.2.7 on 2021-12-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0001_initial'),
        ('fm', '0004_remove_product_economic_order_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='oic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='admin_area.userdetail', verbose_name='Officer-in-Charge', null=True),
            preserve_default=False,
        ),
    ]
