# Generated by Django 4.0 on 2022-04-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_po_product_has_received_po_product_po_subtotal_and_more'),
        ('fm', '0004_product_for_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='completion_rate',
            field=models.FloatField(default=0, verbose_name='Completion Rate'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_po',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_po', to='purchases.purchaseorder', verbose_name='Last Purchase Order'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='open_po_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Open Purchase Orders'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='po_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Purchase Orders'),
        ),
    ]
