# Generated by Django 3.2.7 on 2021-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0005_category_oic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_review',
            field=models.BooleanField(default=False, verbose_name='For price review?'),
        ),
    ]
