# Generated by Django 4.0 on 2022-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0005_supplier_completion_rate_supplier_last_po_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_stocks',
            field=models.PositiveIntegerField(default=0, verbose_name='Store Stocks'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stocks',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Stocks'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_stocks',
            field=models.PositiveIntegerField(default=0, verbose_name='Warehouse Stocks'),
        ),
    ]
