# Generated by Django 4.0 on 2021-12-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0006_product_price_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='oic',
        ),
    ]
