# Generated by Django 4.0 on 2022-04-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0006_product_store_stocks_product_total_stocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest_supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Latest Supplier Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Cancelled at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_updated_on',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Price updated on'),
        ),
    ]
