# Generated by Django 4.0 on 2022-05-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0007_product_latest_supplier_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_review',
        ),
    ]
