# Generated by Django 4.0 on 2021-12-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0007_remove_category_oic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPricing',
        ),
    ]
