# Generated by Django 4.0 on 2022-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0008_delete_productpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('V', 'VAT'), ('X', 'VAT Exempt'), ('Z', 'Zero Rated')], default='V', max_length=15, verbose_name='Tax Type'),
        ),
    ]
