# Generated by Django 4.0 on 2024-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0009_product_avg_inventory_product_cogs_product_itr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tax_class',
            field=models.CharField(blank=True, choices=[('Taxable', 'Taxable'), ('Non-Taxable', 'Non-Taxable'), ('Tax Exempt', 'Tax Exempt'), ('Zero-Rated', 'Zero-Rated')], default=None, max_length=50, null=True, verbose_name='Tax Classification'),
        ),
    ]
