# Generated by Django 4.0 on 2026-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0010_alter_supplier_tax_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Store Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Warehouse Count'),
        ),
    ]
