# Generated by Django 4.0 on 2022-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Grand Total'),
        ),
        migrations.AddField(
            model_name='badorder',
            name='number_of_items',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Items'),
        ),
        migrations.AddField(
            model_name='badorderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Cost'),
        ),
    ]
