# Generated by Django 4.0 on 2022-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badorder',
            name='process_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Process Step'),
        ),
        migrations.AlterField(
            model_name='badorder',
            name='date_discovered',
            field=models.DateField(verbose_name='Date Discovered'),
        ),
    ]
