# Generated by Django 4.0 on 2022-01-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badorder', '0002_badorder_process_step_alter_badorder_date_discovered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badorder',
            old_name='date_cancelled',
            new_name='date_rejected',
        ),
        migrations.RenameField(
            model_name='badorder',
            old_name='cancelled_by',
            new_name='rejected_by',
        ),
        migrations.AddField(
            model_name='badorder',
            name='date_reported',
            field=models.DateField(auto_now=True, verbose_name='Date Reported'),
        ),
        migrations.AddField(
            model_name='badorder',
            name='reject_reason',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Reject reason'),
        ),
    ]
