# Generated by Django 4.0 on 2024-02-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badorder', '0002_badorder_grand_total_badorder_number_of_items_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badorder',
            options={'ordering': ['-pk']},
        ),
    ]
