# Generated by Django 4.0 on 2022-01-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badorder', '0003_rename_date_cancelled_badorder_date_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, verbose_name='Average Unit Price'),
        ),
    ]
