# Generated by Django 4.0 on 2022-01-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badorder', '0004_alter_badorderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='badorder',
            name='in_warehouse',
            field=models.BooleanField(default=True, help_text="True if BO is in the warehouse, otherwise it's in the store.", verbose_name='Is this in the warehouse?'),
        ),
    ]
