# Generated by Django 4.0 on 2021-12-30 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fm', '0008_delete_productpricing'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Retail Price')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Wholesale Price')),
                ('price_updated_on', models.DateField(default=None, null=True, verbose_name='Price updated on')),
                ('price_tagged_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user', verbose_name='Price tagged by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
            ],
        ),
    ]
