# Generated by Django 4.0 on 2022-01-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_type', models.CharField(choices=[('Member', 'Member'), ('Group', 'Group Creditor')], max_length=10, verbose_name='Creditor Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Credit Limit')),
                ('active', models.BooleanField(default=True, help_text='Is this member/creditor still active?', verbose_name='Is active?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Discount name')),
                ('discount_type', models.CharField(choices=[('peso', 'Peso'), ('percent', 'Percent')], max_length=10, verbose_name='Discount Type')),
                ('vatable_only', models.BooleanField(default=False, verbose_name='Apply to Vatable amount only?')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Value')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('vatable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vatable Amount')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT Amount')),
                ('zero_rated', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zero-rated Sales')),
                ('vat_exempt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT-exempt Sales')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount')),
                ('payable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payable Amount')),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date/Time')),
                ('last_reprint', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Reprint')),
                ('cancelled_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Cancelled on')),
                ('cancelled_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by', to='auth.user', verbose_name='Cancelled by')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.creditor', verbose_name='Customer')),
                ('discount_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.discount', verbose_name='Discount Type')),
                ('reprint_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reprinted_by', to='auth.user', verbose_name='Reprinted by')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Supplier Price')),
                ('is_wholesale', models.BooleanField(default=False, verbose_name='Is wholesale?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.product', verbose_name='Product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales', verbose_name='Sales')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
