# Generated by Django 4.0 on 2022-01-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this member/creditor still active?', verbose_name='Is active?'),
        ),
    ]
