# Generated by Django 4.0 on 2022-01-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this discount type still active?', verbose_name='Is active?'),
        ),
    ]
