# Generated by Django 3.2.7 on 2022-02-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20220202_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'get_latest_by': 'pk', 'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='sales',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payable Amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='vat_exempt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT-exempt Sales'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='vatable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vatable Amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='zero_rated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zero-rated Sales'),
        ),
    ]
