# Generated by Django 3.2.7 on 2022-02-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20220202_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-pk']},
        ),
    ]
