# Generated by Django 4.0 on 2022-02-07 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0007_alter_salesitem_supplier_price_salespayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cashier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.user', verbose_name='Cashier'),
        ),
    ]
