# Generated by Django 4.0 on 2022-02-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sales_cashier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='supplier_price',
        ),
        migrations.CreateModel(
            name='SalesItemCogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost of Goods Sold')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Selling Price')),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesitem', verbose_name='Sales Item')),
            ],
        ),
    ]
