# Generated by Django 4.0 on 2022-02-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_salesitem_supplier_price_salesitemcogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitemcogs',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
