# Generated by Django 3.2.7 on 2022-02-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesitemcogs_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='tin',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Tax Identification Number'),
        ),
    ]
