# Generated by Django 4.0 on 2022-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_creditor_tin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='vatable_only',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.AddField(
            model_name='discount',
            name='necessity_only',
            field=models.BooleanField(default=False, help_text='Is this discount for basic necessities or prime commodities only?', verbose_name='For basic necessities or prime commodities only?'),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount_for',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name="Customer's Name"),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount_id_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="Customer's ID number for discount"),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='less_discount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Less: Discount'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='less_vat',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Less: VAT'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='vat_exempt',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='VAT-Exempt'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='vatable',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='VATable'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='zero_rated',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Zero-Rated'),
        ),
    ]
