# Generated by Django 4.0 on 2022-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_discount_vatable_only_remove_sales_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='discount_for',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discount_id_number',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name="Customer's Address"),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_id_card',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name="Customer's ID number for discount"),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_tin',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name="Customer's TIN"),
        ),
    ]
