# Generated by Django 4.0 on 2022-03-01 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0013_rename_discount_for_sales_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cancelled_on',
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_id_card',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name="Customer's ID number"),
        ),
        migrations.CreateModel(
            name='SalesVoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Cancelled on')),
                ('approved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_cancellation_approver', to='auth.user', verbose_name='Approved by')),
                ('cancelled_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by', to='auth.user', verbose_name='Cancelled by')),
                ('sales_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_void', to='sales.salesinvoice', verbose_name='Sales Invoice')),
            ],
        ),
    ]
