# Generated by Django 4.0 on 2022-03-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('sales', '0014_remove_salesinvoice_cancelled_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitemcogs',
            name='cogs',
        ),
        migrations.AddField(
            model_name='salesitemcogs',
            name='store_stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks.storestock', verbose_name='Store Stock Reference'),
            preserve_default=False,
        ),
    ]
