# Generated by Django 4.0 on 2022-03-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0016_alter_sales_options_salesinvoice_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='XReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_removed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT Removed')),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discounts')),
                ('vatable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VATable Sales')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT Amount')),
                ('vatex', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT Exempt Sales')),
                ('zero_rated', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zero Rated Sales')),
                ('items_sold', models.PositiveIntegerField(verbose_name='Number of Items Sold')),
                ('transaction_count', models.PositiveIntegerField(verbose_name='Transaction Count')),
                ('void_count', models.PositiveIntegerField(verbose_name='Void Count')),
                ('void_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Void Total')),
                ('first_si', models.PositiveIntegerField(verbose_name='First Sales Invoice')),
                ('last_si', models.PositiveIntegerField(verbose_name='Last Sales Invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xreading_creator', to='auth.user', verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='ZReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_bal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Beginning Balance')),
                ('ending_bal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ending Balance')),
                ('transaction_count', models.PositiveIntegerField(verbose_name='Transaction Count')),
                ('xreading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.xreading', verbose_name='X-Reading')),
            ],
        ),
        migrations.CreateModel(
            name='TenderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=50, verbose_name='Payment Mode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('xreading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.xreading', verbose_name='X-Reading')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total VAT')),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Discount')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.discount', verbose_name='Discount')),
                ('xreading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.xreading', verbose_name='X-Reading')),
            ],
        ),
    ]
