# Generated by Django 4.0 on 2022-03-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_xreading_zreading_tenderreport_discountreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountreport',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total VAT'),
        ),
    ]
