# Generated by Django 4.0 on 2022-03-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_discountreport_total_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Accempted Value'),
            preserve_default=False,
        ),
    ]
