# Generated by Django 4.0 on 2022-03-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_salespayment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='less_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Less: Discount'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='less_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Less: VAT'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='vat_exempt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT-Exempt'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='vatable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VATable'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='zero_rated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zero-Rated'),
        ),
    ]
