# Generated by Django 4.0 on 2022-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_sales_change_sales_discount_sales_item_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
