# Generated by Django 4.0 on 2024-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_salesinvoice_is_cancelled_salesinvoice_payment_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xreading',
            name='discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discounts'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='items_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Items Sold'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='transaction_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Transaction Count'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='vat_removed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT Removed'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='vatable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VATable Sales'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='vatex',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT Exempt Sales'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='void_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Void Count'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='void_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Void Total'),
        ),
        migrations.AlterField(
            model_name='xreading',
            name='zero_rated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zero Rated Sales'),
        ),
        migrations.AlterField(
            model_name='zreading',
            name='beginning_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Beginning Balance'),
        ),
        migrations.AlterField(
            model_name='zreading',
            name='ending_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ending Balance'),
        ),
        migrations.AlterField(
            model_name='zreading',
            name='void_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Beginning Balance'),
        ),
    ]
