# Generated by Django 4.0 on 2021-12-22 01:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact number')),
                ('userType', models.CharField(choices=[('Purchaser', 'Purchaser'), ('Officer-In-Charge', 'Officer-In-Charge'), ('Audit Committee', 'Audit Committee'), ('General Manager', 'General Manager')], max_length=20)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'File Maintenance - Unit of Measure'), (2, 'File Maintenance - Category'), (3, 'File Maintenance - Supplier'), (4, 'File Maintenance - Product'), (5, 'Transaction - Purchases'), (6, 'Transaction - Price Management'), (7, 'Transaction - Requisition Voucher')], max_length=13)),
                ('activated_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Activated at')),
                ('cancelled_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Cancelled at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to='auth.user')),
            ],
        ),
    ]
