# Generated by Django 4.0 on 2022-01-20 09:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Store Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('registration_number', models.CharField(blank=True, help_text='Please include the registration type.', max_length=50, null=True, verbose_name='Registration Number')),
                ('contact_numbers', models.CharField(blank=True, help_text='Please indicate the type. Separate different contact numbers by comma. E.g., Telephone number: 111-2222', max_length=100, null=True, verbose_name='Contact Numbers')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('vatable', models.BooleanField(default=False, verbose_name='Is the store VATable?')),
                ('vat_percent', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='VAT Percentage')),
                ('point_of_reference', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Point of Reference')),
                ('retail_markup_below', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Retail Markup Below Point of Reference')),
                ('retail_markup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Retail Markup From Point of Reference')),
                ('wholesale_markup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wholesale Markup')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact number')),
                ('userType', models.CharField(choices=[('Member/Creditor', 'Member/Creditor'), ('Warehouse Staff', 'Warehouse Staff'), ('Sales Personnel', 'Sales Personnel'), ('Storekeeper', 'Storekeeper'), ('Purchaser', 'Purchaser'), ('Officer-In-Charge', 'Officer-In-Charge'), ('Audit Committee', 'Audit Committee'), ('General Manager', 'General Manager')], max_length=20)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'File Maintenance - Unit of Measure'), (2, 'File Maintenance - Category'), (3, 'File Maintenance - Supplier'), (4, 'File Maintenance - Product'), (10, 'File Maintenance - Creditors'), (5, 'Transaction - Purchases'), (6, 'Transaction - Price Management'), (7, 'Transaction - Stock Management'), (8, 'Transaction - Requisition Voucher'), (12, 'Transaction - Bad Orders'), (9, 'Reports - Product History'), (11, 'Members - Transactions')], max_length=50)),
                ('activated_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Activated at')),
                ('cancelled_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Cancelled at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
