# Generated by Django 4.0 on 2022-01-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_area', '0001_initial'),
        ('sales', '0001_initial'),
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='linked_creditor_acct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.creditor', verbose_name='If Member/Creditor, link account to'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='oic_for',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fm.category', verbose_name='If OIC, select category'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to='auth.user'),
        ),
    ]
