# Generated by Django 4.0 on 2021-12-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0006_product_price_review'),
        ('admin_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='oic_for',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fm.category'),
        ),
    ]
