# Generated by Django 4.0 on 2021-12-26 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0006_product_price_review'),
        ('admin_area', '0002_userdetail_oic_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Store Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('registration_number', models.CharField(blank=True, help_text='Please include the registration type.', max_length=50, null=True, verbose_name='Registration Number')),
                ('contact_numbers', models.CharField(blank=True, help_text='Please indicate the type. Separate different contact numbers by comma. E.g., Telephone number: 111-2222', max_length=100, null=True, verbose_name='Contact Numbers')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('vatable', models.BooleanField(default=False, verbose_name='Is the store VATable?')),
                ('vat_percent', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='VAT Percentage')),
                ('retail_markup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Retail Markup')),
                ('wholesale_markup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wholesale Markup')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='oic_for',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fm.category', verbose_name='If OIC, select category'),
        ),
    ]
