# Generated by Django 3.2.7 on 2022-02-02 01:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'File Maintenance - Unit of Measure'), (2, 'File Maintenance - Category'), (3, 'File Maintenance - Supplier'), (4, 'File Maintenance - Product'), (10, 'File Maintenance - Creditors'), (5, 'Transaction - Purchases'), (6, 'Transaction - Price Management'), (7, 'Transaction - Stock Management'), (8, 'Transaction - Requisition Voucher'), (12, 'Transaction - Bad Orders'), (13, 'Transaction - Point-of-Sale'), (9, 'Reports - Product History'), (11, 'Members - Transactions')], max_length=50),
        ),
    ]
