# Generated by Django 4.0 on 2021-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0003_store_alter_userdetail_oic_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='point_of_reference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Point of Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='retail_markup_below',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Retail Markup Below Point of Reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='retail_markup',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Retail Markup From Point of Reference'),
        ),
    ]
