# Generated by Django 4.0 on 2021-12-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0004_store_point_of_reference_store_retail_markup_below_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='userType',
            field=models.CharField(choices=[('Warehouse Staff', 'Warehouse Staff'), ('Sales Personnel', 'Sales Personnel'), ('Storekeeper', 'Storekeeper'), ('Purchaser', 'Purchaser'), ('Officer-In-Charge', 'Officer-In-Charge'), ('Audit Committee', 'Audit Committee'), ('General Manager', 'General Manager')], max_length=20),
        ),
    ]
