# Generated by Django 4.0 on 2022-03-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('admin_area', '0004_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='linked_creditor_acct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.creditor', verbose_name='If Member/Creditor, link account to'),
        ),
    ]
