# Generated by Django 4.0 on 2021-12-30 07:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0005_alter_userdetail_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'File Maintenance - Unit of Measure'), (2, 'File Maintenance - Category'), (3, 'File Maintenance - Supplier'), (4, 'File Maintenance - Product'), (5, 'Transaction - Purchases'), (6, 'Transaction - Price Management'), (7, 'Transaction - Stock Management'), (7, 'Transaction - Requisition Voucher')], max_length=15),
        ),
    ]
