# Generated by Django 4.0 on 2022-01-17 08:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0007_alter_userdetail_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'File Maintenance - Unit of Measure'), (2, 'File Maintenance - Category'), (3, 'File Maintenance - Supplier'), (4, 'File Maintenance - Product'), (10, 'File Maintenance - Creditors'), (5, 'Transaction - Purchases'), (6, 'Transaction - Price Management'), (7, 'Transaction - Stock Management'), (8, 'Transaction - Requisition Voucher'), (9, 'Reports - Product History')], max_length=50),
        ),
    ]
