# Generated by Django 4.0 on 2022-01-18 02:43

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('admin_area', '0008_featurelist_alter_userdetail_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='linked_creditor_acct',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.creditor', verbose_name='If Member/Creditor, link account to'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'File Maintenance - Unit of Measure'), (2, 'File Maintenance - Category'), (3, 'File Maintenance - Supplier'), (4, 'File Maintenance - Product'), (10, 'File Maintenance - Creditors'), (5, 'Transaction - Purchases'), (6, 'Transaction - Price Management'), (7, 'Transaction - Stock Management'), (8, 'Transaction - Requisition Voucher'), (9, 'Reports - Product History'), (11, 'Members - Transactions')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userType',
            field=models.CharField(choices=[('Member/Creditor', 'Member/Creditor'), ('Warehouse Staff', 'Warehouse Staff'), ('Sales Personnel', 'Sales Personnel'), ('Storekeeper', 'Storekeeper'), ('Purchaser', 'Purchaser'), ('Officer-In-Charge', 'Officer-In-Charge'), ('Audit Committee', 'Audit Committee'), ('General Manager', 'General Manager')], max_length=20),
        ),
    ]
