# Generated by Django 4.0 on 2022-01-18 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0009_alter_product_tax_type'),
        ('sales', '0001_initial'),
        ('admin_area', '0009_userdetail_linked_creditor_acct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='linked_creditor_acct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.creditor', verbose_name='If Member/Creditor, link account to'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='oic_for',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fm.category', verbose_name='If OIC, select category'),
        ),
    ]
