# Generated by Django 4.0 on 2023-12-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0010_alter_userdetail_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='wholesale_markup_below',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The wholesale markup to be applied from the point of reference and below.', max_digits=5, verbose_name='Wholesale Markup Up To Point of Reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='point_of_reference',
            field=models.DecimalField(decimal_places=2, help_text='The price that will be used as basis for markup computation.', max_digits=5, verbose_name='Point of Reference'),
        ),
        migrations.AlterField(
            model_name='store',
            name='retail_markup',
            field=models.DecimalField(decimal_places=2, help_text='The retail markup to be applied above the point of reference.', max_digits=5, verbose_name='Retail Markup Above Point of Reference'),
        ),
        migrations.AlterField(
            model_name='store',
            name='retail_markup_below',
            field=models.DecimalField(decimal_places=2, help_text='The retail markup to be applied from the point of reference and below.', max_digits=5, verbose_name='Retail Markup Up To Point of Reference'),
        ),
        migrations.AlterField(
            model_name='store',
            name='wholesale_markup',
            field=models.DecimalField(decimal_places=2, help_text='The wholesale markup to be applied above the point of reference.', max_digits=5, verbose_name='Wholesale Markup Above Point of Reference'),
        ),
    ]
