# Generated by Django 4.0 on 2023-12-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0012_remove_store_point_of_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='wholesale_point_of_reference',
            field=models.DecimalField(decimal_places=2, help_text='The price that will be used as basis for markup computation of wholesale price. In pesos.', max_digits=7, verbose_name="Wholesale Price's Point of Reference "),
        ),
    ]
