# Generated by Django 4.0 on 2026-01-01 14:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_area', '0013_alter_store_wholesale_point_of_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'File Maintenance - Unit of Measure'), (2, 'File Maintenance - Category'), (3, 'File Maintenance - Supplier'), (4, 'File Maintenance - Product'), (18, 'File Maintenance - Discount'), (10, 'File Maintenance - Creditors'), (5, 'Transaction - Purchases'), (6, 'Transaction - Price Management'), (7, 'Transaction - Stock Management'), (8, 'Transaction - Requisition Voucher'), (12, 'Transaction - Bad Orders'), (16, 'Transaction - Stock Adjustment'), (13, 'Transaction - Point-of-Sale'), (9, 'Reports - Product History'), (14, 'Reports - Critical Level Products'), (15, 'Reports - Inventory Turnover Ratio'), (11, 'Members - Transactions')], max_length=50),
        ),
    ]
