# Generated by Django 4.0 on 2022-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_type', models.CharField(choices=[('Member', 'Member'), ('Group', 'Group Creditor')], max_length=10, verbose_name='Creditor Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('tin', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Tax Identification Number')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Credit Limit')),
                ('active', models.BooleanField(default=True, help_text='Is this member/creditor still active?', verbose_name='Is active?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
