# Generated by Django 4.0 on 2022-03-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Less: Discount')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Date Posted')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.creditor', verbose_name='Creditor')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Posted by')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
