# Generated by Django 4.0 on 2022-04-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_creditorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditorpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid'),
        ),
    ]
