# Generated by Django 4.0 on 2022-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_creditorpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payable'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='remaining_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remaining Credit'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Charges'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Payments'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='total_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Transaction Amount'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='transaction_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Transaction Count'),
        ),
    ]
