# Generated by Django 4.0 on 2023-12-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_creditor_payable_creditor_remaining_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='id_number',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, unique=True, verbose_name='ID Number'),
        ),
    ]
